// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "da1f219f-9135-4df2-b36f-08931c7a569e";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onTextChange();
void onLed1Change();

String text;
float mpu;
bool led1;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(text, READWRITE, ON_CHANGE, onTextChange);
  ArduinoCloud.addProperty(mpu, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(led1, READWRITE, ON_CHANGE, onLed1Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
